from .cogagent_model import CogAgentModel, FineTuneTrainCogAgentModel, FineTuneTestCogAgentModel
from .cogvlm_model import CogVLMModel, FineTuneTrainCogVLMModel, FineTuneTestCogVLMModel
from .cogagent_new import CogAgentModelNew, FineTuneTrainCogAgentModelNew, FineTuneTestCogAgentModelNew